Add tests and documentation for datastax driver SSL integration
micronaut-projects/micronaut-cassandra pull request #403
Opened 2024-01-18 18:24 UTC by wetted

closes #2 

- [ ]  add tests
- [ ]  add documentation

2024-01-19 09:22 UTC, timyates requested changes
Does this work?  Don't we need to do something to add the certificate to cassandra running in the container?

Can we add a test in here that verifies:

1. The connection is using SSL
2. Queries can be made against cassandra

2024-01-19 09:22 UTC, timyates commented on tests/cassandra-ssl/build.gradle
> +    testRuntimeOnly("ch.qos.logback:logback-classic")
These should use the catalogue `libs....` or `mn....`

2024-01-19 09:22 UTC, timyates commented on tests/cassandra-ssl/src/test/groovy/example/CassandraSSLConfigSpec.groovy
> +                    .withExposedPorts(9042)
```suggestion
    @Shared
    @AutoCleanup
    CassandraContainer cassandraContainer = new CassandraContainer<>(DockerImageName.parse("cassandra:latest"))
            .withExposedPorts(9042)
```

2024-01-19 09:22 UTC, timyates commented on tests/cassandra-ssl/src/test/groovy/example/CassandraSSLConfigSpec.groovy
> +        result
This isn't required.... if it's null, the next line will show that

2024-01-23 18:52 UTC, wetted commented
Still trying to get this working. See also: #404

2024-01-24 22:51 UTC, wetted commented
The Sonarcloud complaint about test coverage is bogus (wrong).

2024-01-25 10:43 UTC, timyates requested changes
Couple of tweaks suggested for the docs?

2024-01-25 10:43 UTC, timyates commented on src/main/docs/guide/ssl.adoc
> +        key-store-password: 12345
This is `truststore`, not `trust-store`

And `keystore`, not `key-store`

We don't need the `cypher-suites` in a minimal example either as far as I know... 🤔 

I would take the minimal example from the ssl test, ie:

```yaml
cassandra:
  default:
    advanced:
      ssl-engine-factory:
                class: DefaultSslEngineFactory
                truststore-path: <path to trust store>
                truststore-password: 12345
```

2024-01-25 10:43 UTC, timyates commented on src/main/docs/guide/ssl.adoc
> +        key-store-password: 12345
I don't think we need any more of the config that follows

2024-01-25 10:43 UTC, timyates commented on src/main/docs/guide/ssl.adoc
> +- cipher-suites: cipher suites to enable when creating a connection
I'd remove this

2024-01-25 10:43 UTC, timyates commented on src/main/docs/guide/ssl.adoc
> +- trust-store and key-store properties: these are optional and if not present the system property configuration is used instead
Make sure these are spelled correctly as per the docs.  keystore isn't required either in the tests, so I'd remove it

2024-01-26 10:46 UTC, timyates approved these changes

2024-01-26 11:40 UTC, merged